# Site settings
title: "Writing a computing system from scratch"
author: "Simon Brand"
description: ""
keywords: ""
biography: ""
colophon: "© 2016 by Simon Brand.<br>This site is hosted at <a href='https://pages.github.com/'>Github Pages</a> and created with <a href='http://jekyllrb.com/'>Jekyll</a>."

baseurl: ""
url: "http://tartanllama.github.io/PantsSys"

google-analytics: UA-86837989-2

simple_search: http://google.com/search
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/

blog: tartanllama.github.io
github_username: TartanLlama
twitter_username: TartanLlama
linkedin_username: simon-brand-36520857
